---
title: "Untitled"
format: html
---

```{r}
library(tidyverse)
```

```{r}
data <- read_csv("data/data_csv.csv")
data
```

```{r}
data <- read_delim("data/data_csv.csv", delim = ",", n_max = 10)
data
```

```{r}
write_delim(data, "out/data_csv.csv", delim = ",")
list.files("out")
```

```{r}
data2 <- read_csv2("data/data_csv2.csv")
data2
```

```{r}
write_csv(data, "out/data_csv.csv")
list.files("out")
```

```{r}
write_excel_csv(data, "out/data_csv.csv")
list.files("out")
```
```{r}
write_csv2(data, "out/data_csv2.csv")
list.files("out")
```

```{r}
write_tsv(data, "out/data_tsv.tsv")
list.files("out")
```

```{r}
data <- read_tsv("data/data_tsv.tsv")
data
```

```{r}
readxl::read_excel("data/data_excel.xlsx", sheet = "data")
```

```{r}
openxlsx::write.xlsx(data, "out/data_excel.xlsx", colNames = TRUE)
```

```{r}
read_rds("data/data_rds.rds")
write_rds(data, "out/data_rds.rds")
```

```{r}
data$`Группа крови`

data[["Группа крови"]] # то же самое, другой синтаксис
```

```{r}
tibble(
  var_first = 1:10,
  var_second = var_first^2
)

tibble(
  var_first = 1:10,
  var_second = if_else(var_first < 5, var_first + 100, var_first)
)
```

```{r}
tibble(
    var_first = 1:10, 
    var_second = ifelse(var_first < 5, var_first + 100, var_first)
    )
```

```{r}
tibble(
    `var 1` = 1:10, 
    `var 2` = `var 1` * 100
    )
```

```{r}
data |> 
    add_column(just_column = "just values", .before = 1)
```

```{r}
data |> 
    add_row(Группа = "New group", Возраст = 100, .before = 1)
```

```{r}
data |> 
    mutate(ID = row_number())
```

```{r}
data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)

data
```

```{r}
data |> select(starts_with("б"))
data |> select(ends_with("_E1"))
data |> select(matches("_E\\d{1}"))
```

```{r}
data |> select(`Пол`, `Группа`, `Базофилы_E1`)
```

```{r}
data |> filter(near(Эозинофилы_E1, 3.38, tol = 0.1))
```

```{r}
data |> mutate(across(!contains("E1"), function(x) str_c(x, " + некая строка")))
```

```{r}
data |>
  mutate(
    `Группа крови` = as.character(`Группа крови`),
    `Группа крови` = replace_na(`Группа крови`, "Нет данных")
  )
```

```{r}
data |>
  mutate(
    `Базофилы_E1` = if_else(
      is.na(`Базофилы_E1`),
      mean(`Базофилы_E1`, na.rm = TRUE),
      `Базофилы_E1`
    )
  )

data |>
  mutate(
    `Группа крови` = as.character(`Группа крови`),
    `Группа крови` = replace_na(`Группа крови`, "Нет данных")
  )

data |>
  mutate(`Группа крови` = fct_na_value_to_level(`Группа крови`, "Нет данных"))

data |>
  mutate(`Группа крови` = na_if(`Группа крови`, "B (III)"))

data |>
  mutate(
    `Группа крови` = fct_na_level_to_value(
      `Группа крови`,
      extra_levels = "B (III)"
    )
  )
```

```{r}
data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), function(x) mean(x, na.rm = TRUE)))

statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)

data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)
```

```{r}
data |>
  group_by(`Группа`) |>
  summarise(n = length(`Группа крови`))
```

```{r}
data <- data |> 
  mutate(`Группа крови` = factor(`Группа крови`))
```

```{r}
data |>
  select(`Группа`, where(is.factor)) |>
  mutate(
    `Группа крови` = fct_na_value_to_level(`Группа крови`, "Нет данных")
  ) |>
  count(`Группа`, `Группа крови`) |>
  group_by(`Группа`) |>
  mutate(`Процент по группе` = n / sum(n) * 100) |>
  ungroup() |>
  mutate(`Процент по выборке` = n / sum(n) * 100) |>
  mutate(across(starts_with("Процент"), function(x) str_c(round(x, 2), "%")))
```

```{r}
data |> distinct(`Группа`)
```

```{r}
tibble(var = "first part__second_part") |>
  separate(var, into = c("var_1", "var_2"), sep = "__")

tibble(var = "first part__second_part") |>
  separate(var, into = c("var_1", "var_2"), sep = "__") |>
  unite("new_var", var_1, var_2, sep = " AND ")
```

```{r}
data_1 <- tibble(var_1 = 1:10, var_2 = rep(c("Группа 1", "Группа 2"), 5))
data_2 <- tibble(var_2 = runif(10, 0, 1), var_3 = rnorm(10))
data_3 <- tibble(var_4 = 100:91, var_5 = rep(c("Молодые", "Средний возраст"), 5))

data_1 |>
  bind_cols(data_2) |>
  bind_cols(data_3)
```

```{r}
data_1 <- tibble(var_1 = "var 1", var_2 = "var 2", var_3 = "var 3")
data_2 <- tibble(var_1 = "var 1", var_2 = "var 2")
data_3 <- tibble(var_1 = "var 1", var_2 = "var 2")

data_1 |>
  bind_rows(data_2) |>
  bind_rows(data_3)
```

```{r}
data_1 <- tibble(var_1 = 1:8) |>
  mutate(id = row_number())

data_2 <- tibble(var_2 = LETTERS) |>
  mutate(`Subject ID` = row_number()) |>
  slice(-1)

data_1
data_2

data_1 |>
  left_join(data_2, by = c("id" = "Subject ID"))

data_1 |>
  right_join(data_2, by = c("id" = "Subject ID"))

data_1 |>
  inner_join(data_2, by = c("id" = "Subject ID"))

data_1 |>
  full_join(data_2, by = c("id" = "Subject ID"))
```

```{r}
data |>
  select(Группа, contains("E1")) |>
  mutate(ID = row_number()) |>
  pivot_longer(!c(Группа, ID))
```

```{r}
data |>
  select(Группа, contains("E1")) |>
  mutate(ID = row_number()) |>
  pivot_longer(!c(Группа, ID)) |>
  pivot_wider(id_cols = c(ID, Группа))
```

```{r}
data |>
  rename_with(function(x) str_replace_all(x, c("_E1" = "1", "_E2" = "2")))
```

```{r}
data |>
  rename_with(.cols = where(is.numeric), .fn = function(x) str_c(x, " КОЛИЧЕСТВЕННАЯ ПЕРЕМЕННАЯ"))
```

```{r}
library(tidyverse)
library(flextable)
```

```{r}
data <- read_tsv("data/data_tsv.tsv", show_col_types = FALSE)
data$Группа <- factor(data$Группа)
data$Пол <- factor(data$Пол)
data$`Группа крови` <- factor(
  data$`Группа крови`,
  levels = c("O (I)", "A (II)", "B (III)", "AB (IV)")
)
```

```{r}
statistics <- list(
  `Количество субъектов` = ~ length(.x),
  `Количество (есть данные)` = ~ sum(!is.na(.x)),
  `Нет данных` = ~ sum(is.na(.x)),
  `Ср. знач.` = ~ mean(.x, na.rm = TRUE),
  `Станд. отклон.` = ~ sd(.x, na.rm = TRUE),
  `мин.` = ~ min(.x, na.rm = TRUE),
  `макс.` = ~ max(.x, na.rm = TRUE),
  `Медиана` = ~ median(.x, na.rm = TRUE),
  `Q1` = ~ quantile(.x, 0.25, na.rm = TRUE),
  `Q3` = ~ quantile(.x, 0.75, na.rm = TRUE)
)

table <- data |>
  select(`Группа`, where(is.numeric)) |>
  group_by(`Группа`) |>
  summarise(across(where(is.numeric), statistics, .names = "{.col}__{.fn}")) |>
  mutate(across(-`Группа`, function(x) round(x, 2))) |>
  mutate(across(-`Группа`, as.character)) |>
  mutate(across(-`Группа`, function(x) replace_na(x, "Н/П*"))) |>
  pivot_longer(!`Группа`) |>
  separate(name, into = c("Переменная", "Статистика"), sep = "__") |>
  rename(`Значение` = value)
```

```{r}
table |>
  flextable() |>
  theme_box()
```

```{r}
table |>
  flextable() |>
  theme_alafoli()
```

```{r}
table |>
  flextable() |>
  theme_box() |>
  merge_v(c("Группа", "Переменная"))
```

```{r}
tibble(var_1 = c("p-value", "0.001"),
       var_2 = c("p-value", "0.05")) |>
  flextable() |>
  theme_box() |>
  merge_h(i = 1)
```

```{r}
table <- tibble(`Adverse events` = c("SOC Желудочно-кишечные нарушения 10017947",
                                     "PT Тошнота 10028813",
                                     "SOC Нарушения со стороны нервной системы 10029205",
                                     "PT Головная боль 10019211"))

table |>
  flextable() |>
  theme_box() |>
  align(align = "center", part = "all")
```

```{r}
table |>
  flextable() |>
  theme_box() |>
  align(i = ~ str_detect(`Adverse events`, "SOC"), align = "left") |>
  align(i = ~ str_detect(`Adverse events`, "PT"), align = "right") |>
  width(width = 2)
```

```{r}
table <- tibble(`Adverse events` = c("SOC Желудочно-кишечные нарушения 10017947",
                                     "PT Тошнота 10028813",
                                     "SOC Нарушения со стороны нервной системы 10029205",
                                     "PT Головная боль 10019211"))

table |>
  flextable() |>
  theme_box() |>
  align(i = ~ str_detect(`Adverse events`, "SOC"), align = "left") |>
  align(i = ~ str_detect(`Adverse events`, "PT"), align = "right") |>
  bold(i = ~ str_detect(`Adverse events`, "SOC")) |>
  italic(i = ~ str_detect(`Adverse events`, "PT")) |>
  width(width = 2)
```

```{r}
is_pvalue_sign <- function(x) {
  as.numeric(str_remove(x, "<")) <= 0.05
}

table <- tibble("p-value" = c("<0.001", "0.38", "0.124", "0.005", "0.05"))

table |>
  flextable() |>
  theme_box() |>
  color(i = ~ is_pvalue_sign(`p-value`), color = "orange")
```

```{r}
table |>
  flextable() |>
  theme_box() |>
  bg(i = ~ is_pvalue_sign(`p-value`), bg = "orange")
```

```{r}

```